version = 1

[market]
symbol = "BTC/USDT"

[output]
format = "terminal"
verbose = false

[sources."candles@binancef@mmt"]
timeframe = 60

[sources."orderbook@bulk"]
depth = 20

[script]
path = "./examples/sma-crossover.js"

[script.params]
max_spread = 1
max_slippage = 0.1
entry_amount_dollar = 150
leverage = 5

[execution]
venue = "bulk"
